name: Sync Website Repo

on:
  push:
    branches:
      - master

jobs:
  sync-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Website Repo
        uses: actions/checkout@v3
        with:
          repository: isaacbernat/netflix-to-srt-web
          path: website

      - name: Start SSH Agent
        uses: actions/setup-ssh-agent@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
  
      - name: Check SSH Agent
        run: ssh-add -l
  
      - name: Test SSH Connection
        run: ssh -T git@github.com

      - name: Deploy Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: 'just_accept'

      - name: Configure Git
        run: |
          cd website
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Copy Web Files
        run: |
          cd dev_repo
          cp index.html ../website/
          cp script.js ../website/
          cp style.css ../website/
          cp robots.txt ../website/

      - name: Commit and Push Changes to Website Repo
        run: |
          cd website
          git add .
          git commit -m "Updated website from dev repo"
          git push origin main
