name: Sync Website Repo

on:
  push:
    branches:
      - master

jobs:
  sync-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Website Repo
        uses: actions/checkout@v4
        with:
          repository: isaacbernat/netflix-to-srt-web
          path: website
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Development Repo
        uses: actions/checkout@v4
        with:
          repository: isaacbernat/netflix-to-srt
          path: dev_repo

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s) # Start the SSH agent
          ssh-add ~/.ssh/id_rsa # Add the key to the agent
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"

      - name: Configure Git
        run: |
          cd website
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Copy Web Files
        run: |
          cd dev_repo
          cp -r web/* ../website/

      - name: Commit and Push Changes to Website Repo
        run: |
          cd website
          git add .
          git commit -m "Updated website from dev repo"
          git push git@github.com:isaacbernat/netflix-to-srt-web.git main
